### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by tvvocold** [transOSTeam/transOS#2]
http://www.chinacloud.cn/upload/2012-10/12101315477588.pdf

**Comment by anuragpeshne** [comment]
Both are totally different. "TransOS (Transparent Operating System) is a project aimed to help in classroom teaching of Operating System Course."
Where as  cloud operating system, TransOS, from the viewpoint of transparent computing, in which
all traditional operating system codes and applications are centrally stored on network servers, and an almost bare terminal dynamically schedules the necessary codes selected by users from the network server, and runs them mostly with the terminal’s local resources. Have a look at readme files to get a better idea.
